### ISSUE TITLE
[HELP][MAGIC NUMBERS] What the hell are these numbers?

### ISSUE THREAD

**Issue by Stooberton** [ACF-Team/ACF-3#179]
**Short Description**
`6.45` may be an arbitrary number to tweak something.
`0.52505066107` may be some unit conversion.

https://github.com/Stooberton/ACF-3/blob/d9b03efc42d1f02028a05dc1c57e26fdaa172459/lua/acf/base/sv_validation.lua#L136-L150

**Comment by thegrb93** [comment]
6.45 is a magic number https://github.com/nrlulz/ACF/commit/d323b90aa3f6421a660ae9a373d95737f06da620

**Comment by thegrb93** [comment]
But it's also in^2 to cm^2 https://www.google.com/search?q=in%5E2+to+cm%5E2

**Comment by thegrb93** [comment]
16.38 is in^3 to cm^3 https://www.google.com/search?q=in%5E3+to+cm%5E3

**Comment by thegrb93** [comment]
Not sure about 0.52505066107. It was added here https://github.com/nrlulz/ACF/commit/712152af588a2f626bb630dbc50a81a6e9ba765f

**Comment by Stooberton** [comment]
Here's another: `0.4774`

https://github.com/Stooberton/ACF-3/blob/d9b03efc42d1f02028a05dc1c57e26fdaa172459/lua/entities/acf_fueltank/init.lua#L91

**Comment by Stooberton** [comment]
> Here's another: `0.4774`
> 
> https://github.com/Stooberton/ACF-3/blob/d9b03efc42d1f02028a05dc1c57e26fdaa172459/lua/entities/acf_fueltank/init.lua#L91

This appears to be in actuality a completely arbitrary value to tweak the volume calculated from the volume of the fuel tank models, as they aren't regular cuboids.

With the introduction of procedural tanks this particular number can be eliminated as the procedural tanks will have a known volume.

**Comment by thecraftianman** [comment]
Could the 0.525... number possibly be an attempt to account for Source grid units? The inverse of this number is very similar to the value of 1 unit on the architectural scale. https://developer.valvesoftware.com/wiki/Dimensions_(Half-Life_2_and_Counter-Strike:_Source)

**Comment by thecraftianman** [comment]
After a bit of discussion on Discord, this seems to be exactly what that multiplier is for. Both the 6.45 and 0.525 values will now be documented as such going forwards.
