### ISSUE TITLE
[BUG] ACF glowing decals

### ISSUE THREAD

**Issue by EvgheshkaFX** [ACF-Team/ACF-3#253]
All ACF decals start to glow when:
You take a prop with a physgun
You look at the ACF component
**Video:**
https://www.dropbox.com/s/igbzhe1r0f4tp0s/chrome_OSJEUPeL6W.mp4?dl=0

**Comment by thecraftianman** [comment]
Is this still a thing? I've tried to replicate this, but I haven't had any luck in getting this to happen nowadays.

**Comment by thecraftianman** [comment]
Checked in on this one again and I was told that the issue had resolved itself a long time ago. I'm closing this because I can't find any other mentions of this problem besides this issue.
