### ISSUE TITLE
[SUGGESTION] Add Contraption Framework to ACF

### ISSUE THREAD

**Issue by Stooberton** [ACF-Team/ACF-3#27]
**Short Description**

Add Contraption Framework in order to greatly simplify and speed up contraption-aware functionality in ACF.

**References (Optional)**

https://github.com/Stooberton/cframe

**Comment by TechnichalDoge** [comment]
any updates?

**Comment by Stooberton** [comment]
Contraption Framework is a big project unto itself and definitely shouldn't be considered for integrating any time soon.

**Comment by thecraftianman** [comment]
I think we're reconsidering this one now; adding CFW support would help resolve a currently existing conflict between it and ACF's turret entities (see ACF-Team/CFW@f91bcd8), and we could use it for some new features that would otherwise be more difficult to implement (ie. baseplate legal checks?)
