### ISSUE TITLE
[SUGGESTION] Method to override default effects

### ISSUE THREAD

**Issue by TwistedTail** [ACF-Team/ACF-3#321]
**Short Description**

There's always the possibility someone might not be comfortable with the effects on the mod and decides to make their own. It'd be a nice addition to make this kind of task as free from overrides as possible by providing a hook that gets called every time an effect is created by ACF. That way people won't have to mess with ACF code or override vanilla effect functions by adding pointless overhead.

**Comment by thecraftianman** [comment]
Added the hook `ACF_PreCreateEffect` in 28916bc to allow overriding effect names and attributes for ACF-produced effects.
