### ISSUE TITLE
[BUG] Starfall and E2's :acfCaliber() function always returns 0 when used on missile racks

### ISSUE THREAD

**Issue by ProfessorBoxtrot** [ACF-Team/ACF-3#325]
**Branch and Version**

Latest version, master branch

**How to Reproduce**

Spawn this Starfall chip on any ACF Missiles rack:

```
--@server
print(chip():isWeldedTo():acfCaliber())
```

It will always print 0, even if the rack is currently loaded. Same result for its E2 equivalent:

```
print(entity():isWeldedTo():acfCaliber())
```

Using it on the ammo crate the rack is linked to instead will give the correct result.

**Comment by Goodva** [comment]
this is an [ACF3 Missiles](https://github.com/TwistedTail/ACF-3-Missiles) thing btw

**Comment by ProfessorBoxtrot** [comment]
wasn't sure whether to post it here or on missiles, I'm not sure if it's an issue with ACF missiles racks themselves or the starfall functions used to access their caliber.

**Comment by TwistedTail** [comment]
It's fine here. The issue comes from racks not storing any bullet data from the selected missile on themselves, which should be fairly simple to solve.
