### ISSUE TITLE
HEAT falloff way too slow from a balance perspective [SUGGESTION]

### ISSUE THREAD

**Issue by LengthenedGradient** [ACF-Team/ACF-3#357]
**Short Description**

This ties in partially with the bug I mentioned for radio fuses (https://github.com/Stooberton/ACF-3/issues/356) since you currently have to use contact fuses for antimissile guidance. In the case that you do use contact fuse / when the radio fuse sometimes fails to trigger before collision, an antimissile missile will cause an incoming atgm to believe it's impacted a prop and trigger the warhead, causing a HEAT detonation. As a result, a "HEAT" jet will continue traveling substantial distances until it impacts the tank in question (there is *some* drop but it is marginal), and so antimissile interceptors have even more randomness on top of the normal RNG missile damage model that makes them worse.

The issue is that, due to some experimental results, the penetration missiles like the hellfire have does not falloff until considerable distances away:
- Due to standoff, you don't want to intercept a Hellfire before 16 meters (640u), otherwise it would increase the penetration (>base pen). I've been told this is realistic, though, so less of a concern since it's still a somewhat reasonable distance.
- The penetration only goes down to around 500 after 47 meters (1880u), which is just crazy far out. I have tested and the jet does travel out to at least 4500u (113m)

Here's a link to a graph I made of the Hellfire's penetration (https://www.desmos.com/calculator/2aoqo4ao1u). The coefficients were collected from printing them out in Lua within the get penetration call. I don't think there's any calculation errors but if you find any, do feel free to correct; it seems to match up with the penetration tests I have done.
- The x axis is in meters, y axis in millimeters.

As for fixing it, I suggest modifying the section in the else loop (after the maximum penetration) to control the falloff, https://github.com/Stooberton/ACF-3/blob/392203df7377b1ff22c8985b96dedf5ab500d7a7/lua/acf/entities/ammo_types/heat.lua#L52-L54
- You could do this a number of ways, such as exponentiation the penetration value using a decay function (here g(x) is your decay function and f(x) is the penetration function after bullet breakup). The X argument is the standoff distance.
![image](https://github.com/Stooberton/ACF-3/assets/109800352/05fb7a6b-3671-4d88-a32e-609fa1034bc3)
- There's other solutions two, but short of actually consulting the papers on the topic I don't know how you'd "re balance" something "scientific"

**References (Optional)**

- HEAT Penetration function in ACF Code: https://github.com/Stooberton/ACF-3/blob/392203df7377b1ff22c8985b96dedf5ab500d7a7/lua/acf/entities/ammo_types/heat.lua#L35-L57

**Comment by thecraftianman** [comment]
Should be closed by #386.
