### ISSUE TITLE
[BUG] List of broken things in ACF at the moment

### ISSUE THREAD

**Issue by Goodva** [ACF-Team/ACF-3#373]
Title says it all.

- HEAT does not respect the damage permissions when it comes to damaging the ammoboxes. it just doesnt. i dont know why.
- Procedural armor probably has negative health from the start, or if i put it straight it doesnt die really. ![image](https://github.com/Stooberton/ACF-3/assets/30363060/43e9f2c7-a122-4472-95f0-1446c753deda)
- you can get past the 50t limit and have armor more dense than  lead ![image](https://github.com/Stooberton/ACF-3/assets/30363060/ef4c91a0-ba32-4eb4-8aad-202160d7e1ec)
- updating procedural armor causes in any way, even without changing dimensions, causes it to have mass of 1kg.![image](https://github.com/Stooberton/ACF-3/assets/30363060/9d7a9f21-6a09-4431-93cf-78e28e6dc5a1)
- procedural armor can be shot through and the shell will ignore everything but the world.![image](https://github.com/Stooberton/ACF-3/assets/30363060/c795d55c-ba3f-4f71-988a-a58119203cd6)  ![image](https://github.com/Stooberton/ACF-3/assets/30363060/d691da34-8d5c-4ae5-8b27-85023ad62466)
- HEATFS and missile HEAT do comicaly high amount of postpen damage.
- not really a bug, but i just want to point out that a 300mm piledriver, which weights at 3.6t has spike mass of only ~50kg. you are telling me that a 300mm in diameter spike with a length of almost 3.5m only weights 50kg? 
- also not a bug, but autoloaders beign 3x heavy as a regular cannon makes them worthless, pls make them a bit lighter.

might update with more bugs if i remember smth

**Comment by Goodva** [comment]
edit 1: server version is `Git-master-11fefdc`

**Comment by Stooberton** [comment]
I'm really not concerned with pArmor, it was an experiment and we're not really going anywhere with it at the moment.

How the hell did you get something set past 50k? Is it actually heavier than 50k or is this some kind of calculation bug inside ACF?

**Comment by Goodva** [comment]
it could be that its not heavier than 50t, bcuz when you look at that prop w/ weight tool it says that it weight 50t. on how to reproduce - im not sure, i just maxed out both armor and ductility and it works.

**Comment by thecraftianman** [comment]
> - Procedural armor probably has negative health from the start, or if i put it straight it doesnt die really.

> - procedural armor can be shot through and the shell will ignore everything but the world.

These are happening because you have procedural armor disabled in your settings (it's disabled by default now).

> - you can get past the 50t limit and have armor more dense than lead

> - updating procedural armor causes in any way, even without changing dimensions, causes it to have mass of 1kg.

Should be fixed in the current dev branch.
