### ISSUE TITLE
[SUGGESTION] Add SWEPS for players?

### ISSUE THREAD

**Issue by Mememan97GithubEdition** [ACF-Team/ACF-3#391]
**Short Description**

ACF-3 Sweps for players looking to rp as infantry, basically gun sweps that use acf bullets to damage players
Something like this exists on the workshop but i would like to see if there is a chances something like this is added officially 

**References (Optional)**
[https://steamcommunity.com/sharedfiles/filedetails/?id=2923573966&searchtext=acf+3](url)

**Comment by LiddulBOFH** [comment]
https://github.com/ACF-Team/ACF-3-SWEPs
This might be what you're looking for, its the same addon just slightly behind on an update

**Comment by thecraftianman** [comment]
ACF-3 SWEPs is actually an official extension now, but there's currently no plans to merge it with the base mod at this time.

**Comment by Mememan97GithubEdition** [comment]
oh cool
