### ISSUE TITLE
[BUG] Chair hitbox bug

### ISSUE THREAD

**Issue by Joshua732** [ACF-Team/ACF-3#417]
**Short Description**

The hitbox of non pilot chairs is not correct when duping in a vehicle causing drivers to be shot out. This happens when you save a ADV2 dupe of a tank with a non pilot chair and reopen it and dupe it.

**Branch and Version**

Master(Up to date as I am writing this report.)

**How to Reproduce**

Open a ADV2 file with a non pilot chair vehicle.

**Screenshots**

![image](https://github.com/ACF-Team/ACF-3/assets/103468045/439d70d3-2afb-4acc-b1ef-2c1a59fff7bc)
Chair when taking out.
![image](https://github.com/ACF-Team/ACF-3/assets/103468045/177a7d97-7690-43d3-9f6a-34327e3d85b5)
Video

https://github.com/ACF-Team/ACF-3/assets/103468045/d2b46e09-a09a-4584-ae1b-44d007f51e4f

**Additional Information**

This seems to be related to the Contraption Framework for ACF but can be the ADV2 tool.

**Comment by thecraftianman** [comment]
Should be fixed in https://github.com/ACF-Team/ACF-3/commit/716cac027a566caff5f83ce57a53a877a21f9f3d
