### ISSUE TITLE
[BUG] Parent to a holo cause armor properties tool and recoil to not work

### ISSUE THREAD

**Issue by Joshua732** [ACF-Team/ACF-3#425]
**Short Description**

The ACF armor properties tool can not get the armor of a prop that is parented to a hologram. This causes lots of problems like the recoil of a gun is too huge even if the prop has maxed weight.

**Branch and Version**

Latest(As of this report)

**How to Reproduce (Optional)**

if(first() | dupefinished()) {
    holoCreate(1)
    holoPos(1,Base:pos())
    holoParent(1,Base)
    timer("P",100)
}

if(clk("P")){
    Test:parentTo(holoEntity(1))
}

Wire Base to something and test to the entity that you will read its armor and refresh chip
Use the ACF armor properties tool on the entity that is parented to the hologram and see how the tool does not work.

**Additional Information (Optional)**

We do have turret entities but holoturrets are still popular and this bug cause some tiny problems with the common chips but may make others unusable. You can still read the armor with sphere search but this bug affects recoil of guns.

**Comment by thecraftianman** [comment]
Did this start occurring after today's push to dev? (Specifically the changes from https://github.com/ACF-Team/ACF-3/commit/a0f86704bed1b58f20699559b32ca7944098e48d)

**Comment by Joshua732** [comment]
Yes, When I updated a server today (technically yesterday). That started occurring.

**Comment by TwistedTail** [comment]
Should be fixed on dev with [f30735c](https://github.com/ACF-Team/ACF-3/commit/f30735c65988520d98830913b412b71b088530d2), along with some other issues.
